# Generated by Django 4.2.6 on 2023-11-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
