# Generated by Django 4.2.6 on 2023-11-02 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_alter_reservations_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
